name: campus

on:
  push:
    branches: [CDTEST]
    
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout source code.
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: create env file
        working-directory: ./build
        run: |
          touch .env
          cat << EOF >> .env
          ${{ secrets.ENV }}
      - name: build client files
        working-directory: ./
        run: |
          npm install
      - name: zip file
        run: zip -r campustest.zip ./build ./scripts ./appspec.yml ./env ./package.json

      - name: AWS connect
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: ap-northeast-2

      - name: upload to S3
        run: aws s3 cp --region ap-northeast-2 ./campustest.zip s3://qwerqwer/build/


      - name: deploy with AWS codeDeploy
        run: aws deploy create-deployment
          --application-name campusA
          --deployment-config-name CodeDeployDefault.AllAtOnce
          --deployment-group-name campusA
          --s3-location bucket=qwerqwer,bundleType=zip,key=build/campustest.zip
      
