name: campus

on:
  push:
    branches: [CDTEST]
    
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout source code.
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: create env file
        working-directory: ./build
        run: |
          touch .env
          cat << EOF >> .env
          ${{ secrets.ENV }}
      - name: build client files
        working-directory: ./
        run: |
          npm install
      - name: zip file
        run: zip -r cicdtest.zip ./build ./scripts ./appspec.yml ./env ./package.json

      - name: AWS connect
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1

      - name: upload to S3
        run: aws s3 cp --region ca-central-1 ./cicdtest.zip s3://campus123/build/

      - name: deploy with AWS codeDeploy
        run: aws deploy create-deployment
          --application-name campusautocode
          --deployment-config-name CodeDeployDefault.OneAtATime
          --deployment-group-name campusautocodeGrop
          --s3-location bucket=campus123,bundleType=zip,key=build/cicdtest.zip
      
